name: BuycraftX
main: net.buycraft.plugin.nukkit.BuycraftPlugin
version: "${version}"
author: Buycraft
api: [ 2.0.0 ]
commands:
  tebex:
    aliases: [ buycraft ]
    description: Main command for the Tebex plugin.