/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

dependencies {
    api(project(":buycraftx-common"))
    testImplementation(libs.junit.junit)
}

description = "buycraftx-plugin-shared"
